// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/logboek/v1/logboek.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessingOperation_StatusCode int32

const (
	ProcessingOperation_STATUS_CODE_UNKNOWN ProcessingOperation_StatusCode = 0
	ProcessingOperation_STATUS_CODE_OK      ProcessingOperation_StatusCode = 1
	ProcessingOperation_STATUS_CODE_ERROR   ProcessingOperation_StatusCode = 2
)

// Enum value maps for ProcessingOperation_StatusCode.
var (
	ProcessingOperation_StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNKNOWN",
		1: "STATUS_CODE_OK",
		2: "STATUS_CODE_ERROR",
	}
	ProcessingOperation_StatusCode_value = map[string]int32{
		"STATUS_CODE_UNKNOWN": 0,
		"STATUS_CODE_OK":      1,
		"STATUS_CODE_ERROR":   2,
	}
)

func (x ProcessingOperation_StatusCode) Enum() *ProcessingOperation_StatusCode {
	p := new(ProcessingOperation_StatusCode)
	*p = x
	return p
}

func (x ProcessingOperation_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingOperation_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logboek_v1_logboek_proto_enumTypes[0].Descriptor()
}

func (ProcessingOperation_StatusCode) Type() protoreflect.EnumType {
	return &file_proto_logboek_v1_logboek_proto_enumTypes[0]
}

func (x ProcessingOperation_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingOperation_StatusCode.Descriptor instead.
func (ProcessingOperation_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{3, 0}
}

type ExportOperationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource   *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Operations []*ProcessingOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *ExportOperationsRequest) Reset() {
	*x = ExportOperationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperationsRequest) ProtoMessage() {}

func (x *ExportOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperationsRequest.ProtoReflect.Descriptor instead.
func (*ExportOperationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{0}
}

func (x *ExportOperationsRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExportOperationsRequest) GetOperations() []*ProcessingOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ExportOperationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportOperationsResponse) Reset() {
	*x = ExportOperationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperationsResponse) ProtoMessage() {}

func (x *ExportOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperationsResponse.ProtoReflect.Descriptor instead.
func (*ExportOperationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{1}
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ProcessingOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId           []byte                                          `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	OperationId       []byte                                          `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ParentOperationId []byte                                          `protobuf:"bytes,3,opt,name=parent_operation_id,json=parentOperationId,proto3" json:"parent_operation_id,omitempty"`
	Name              string                                          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartTime         *timestamppb.Timestamp                          `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp                          `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	StatusCode        ProcessingOperation_StatusCode                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3,enum=logboek.v1.ProcessingOperation_StatusCode" json:"status_code,omitempty"`
	ForeignOperation  *ProcessingOperation_ForeignProcessingOperation `protobuf:"bytes,8,opt,name=foreign_operation,json=foreignOperation,proto3" json:"foreign_operation,omitempty"`
	Attributes        []*Attribute                                    `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *ProcessingOperation) Reset() {
	*x = ProcessingOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOperation) ProtoMessage() {}

func (x *ProcessingOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOperation.ProtoReflect.Descriptor instead.
func (*ProcessingOperation) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessingOperation) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *ProcessingOperation) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *ProcessingOperation) GetParentOperationId() []byte {
	if x != nil {
		return x.ParentOperationId
	}
	return nil
}

func (x *ProcessingOperation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessingOperation) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProcessingOperation) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ProcessingOperation) GetStatusCode() ProcessingOperation_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return ProcessingOperation_STATUS_CODE_UNKNOWN
}

func (x *ProcessingOperation) GetForeignOperation() *ProcessingOperation_ForeignProcessingOperation {
	if x != nil {
		return x.ForeignOperation
	}
	return nil
}

func (x *ProcessingOperation) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{4}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProcessingOperation_ForeignProcessingOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId     []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	OperationId []byte `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Entity      string `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *ProcessingOperation_ForeignProcessingOperation) Reset() {
	*x = ProcessingOperation_ForeignProcessingOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logboek_v1_logboek_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingOperation_ForeignProcessingOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOperation_ForeignProcessingOperation) ProtoMessage() {}

func (x *ProcessingOperation_ForeignProcessingOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logboek_v1_logboek_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOperation_ForeignProcessingOperation.ProtoReflect.Descriptor instead.
func (*ProcessingOperation_ForeignProcessingOperation) Descriptor() ([]byte, []int) {
	return file_proto_logboek_v1_logboek_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ProcessingOperation_ForeignProcessingOperation) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *ProcessingOperation_ForeignProcessingOperation) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *ProcessingOperation_ForeignProcessingOperation) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

var File_proto_logboek_v1_logboek_proto protoreflect.FileDescriptor

var file_proto_logboek_v1_logboek_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2f,
	0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01,
	0x0a, 0x17, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f,
	0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1a, 0x0a, 0x18,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xbc, 0x05, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x4b,
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x67, 0x0a, 0x11, 0x66,
	0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x10, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f,
	0x65, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x72, 0x0a, 0x1a, 0x46,
	0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x50, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a,
	0x13, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x22, 0x33, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x67, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x62, 0x6f, 0x65,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x23, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x6f, 0x67, 0x62, 0x6f, 0x65,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logboek_v1_logboek_proto_rawDescOnce sync.Once
	file_proto_logboek_v1_logboek_proto_rawDescData = file_proto_logboek_v1_logboek_proto_rawDesc
)

func file_proto_logboek_v1_logboek_proto_rawDescGZIP() []byte {
	file_proto_logboek_v1_logboek_proto_rawDescOnce.Do(func() {
		file_proto_logboek_v1_logboek_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logboek_v1_logboek_proto_rawDescData)
	})
	return file_proto_logboek_v1_logboek_proto_rawDescData
}

var file_proto_logboek_v1_logboek_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logboek_v1_logboek_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_logboek_v1_logboek_proto_goTypes = []interface{}{
	(ProcessingOperation_StatusCode)(0),                    // 0: logboek.v1.ProcessingOperation.StatusCode
	(*ExportOperationsRequest)(nil),                        // 1: logboek.v1.ExportOperationsRequest
	(*ExportOperationsResponse)(nil),                       // 2: logboek.v1.ExportOperationsResponse
	(*Resource)(nil),                                       // 3: logboek.v1.Resource
	(*ProcessingOperation)(nil),                            // 4: logboek.v1.ProcessingOperation
	(*Attribute)(nil),                                      // 5: logboek.v1.Attribute
	(*ProcessingOperation_ForeignProcessingOperation)(nil), // 6: logboek.v1.ProcessingOperation.ForeignProcessingOperation
	(*timestamppb.Timestamp)(nil),                          // 7: google.protobuf.Timestamp
}
var file_proto_logboek_v1_logboek_proto_depIdxs = []int32{
	3, // 0: logboek.v1.ExportOperationsRequest.resource:type_name -> logboek.v1.Resource
	4, // 1: logboek.v1.ExportOperationsRequest.operations:type_name -> logboek.v1.ProcessingOperation
	7, // 2: logboek.v1.ProcessingOperation.start_time:type_name -> google.protobuf.Timestamp
	7, // 3: logboek.v1.ProcessingOperation.end_time:type_name -> google.protobuf.Timestamp
	0, // 4: logboek.v1.ProcessingOperation.status_code:type_name -> logboek.v1.ProcessingOperation.StatusCode
	6, // 5: logboek.v1.ProcessingOperation.foreign_operation:type_name -> logboek.v1.ProcessingOperation.ForeignProcessingOperation
	5, // 6: logboek.v1.ProcessingOperation.attributes:type_name -> logboek.v1.Attribute
	1, // 7: logboek.v1.LogboekService.Export:input_type -> logboek.v1.ExportOperationsRequest
	2, // 8: logboek.v1.LogboekService.Export:output_type -> logboek.v1.ExportOperationsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_logboek_v1_logboek_proto_init() }
func file_proto_logboek_v1_logboek_proto_init() {
	if File_proto_logboek_v1_logboek_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logboek_v1_logboek_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportOperationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logboek_v1_logboek_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportOperationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logboek_v1_logboek_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logboek_v1_logboek_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logboek_v1_logboek_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logboek_v1_logboek_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingOperation_ForeignProcessingOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logboek_v1_logboek_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logboek_v1_logboek_proto_goTypes,
		DependencyIndexes: file_proto_logboek_v1_logboek_proto_depIdxs,
		EnumInfos:         file_proto_logboek_v1_logboek_proto_enumTypes,
		MessageInfos:      file_proto_logboek_v1_logboek_proto_msgTypes,
	}.Build()
	File_proto_logboek_v1_logboek_proto = out.File
	file_proto_logboek_v1_logboek_proto_rawDesc = nil
	file_proto_logboek_v1_logboek_proto_goTypes = nil
	file_proto_logboek_v1_logboek_proto_depIdxs = nil
}
